include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    avoid_print: false  # Allow print for debugging
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
